[package]
name = "rinnova"
version = "0.1.0"
authors = ["Nigel Eke"]
edition = "2024"

[dependencies]
delegate = "0.13.5"
dioxus = { version = "0.7.10", features = [] }
dioxus-i18n = "0.5.1"
dioxus-sdk = { version = "0.7.0", features = ["storage"] }
gloo-timers = { version = "0.4.0", features = ["futures"] }
jiff = { version = "0.2.34", features = ["js", "serde"] }
rexie = "0.6.2"
serde = { version = "1.0.229", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
thiserror = "2.0.19"
uuid = { version = "1.24.0", features = ["serde", "v7", "js"] }
web-sys = { version = "0.3.103", features = ["Document", "Navigator"] }

[features]
default = ["web"]
web = ["dioxus/web"]
